let shopItemsData = [
  {
    id: "item1",
    name: "Casual Shirt",
    price: "45",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "img/img-1.jpg",
  },
  {
    id: "item2",
    name: "Office Shirt",
    price: "100",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "img/img-2.jpg",
  },
  {
    id: "item3",
    name: "T - Shirt",
    price: "25",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "img/img-3.jpg",
  },
  {
    id: "item4",
    name: "Mens Suit",
    price: "300",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "img/img-4.jpg",
  },
  {
    id: "item5",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-5.png",
  },
  {
    id: "item6",
    name: "Casual Shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-6.png",
  },
  {
    id: "item7",
    name: "Black Suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-7.png",
  },
  {
    id: "item8",
    name: "Polo Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-8.png",
  },
  {
    id: "item9",
    name: "Denim Shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-9.png",
  },
  {
    id: "item10",
    name: "Denim Pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-10.png",
  },
  {
    id: "item11",
    name: "Basic Cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-11.png",
  },
  {
    id: "item12",
    name: "Leather Boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/img-12.png",
  },
];
